const char *strtab[] = {
    "gimme something:",
    "\nCorrect :)\nSurround your flag with dice{}",
    "\nIncorrect :(",
    "\n(1) could be interesting...",
    "secr3t_c0d3",
    "\n(2) hmm...",
    "flag",
    "\n(3) checking flag:",
    "magic",
    "\n(4) validating magic...",
    "bad magic size",
    "bad magic type",
    "magic did not validate",
    "missing magic",
    "wrong magic",
    "{",
    "[",
    "\"",
    "}",
    ":",
    ",",
    "parse error",
    "]",
    "Parse error: expected \"[\"",
    "parse error: invalid string",
};
